INSERT INTO STUDENTS VALUES(1, 'Nargiz', 'Tahmazli', 'BIT');
INSERT INTO STUDENTS VALUES(2, 'Nigar', 'Safarova', 'BIT');
INSERT INTO STUDENTS VALUES(3, 'Sofiya', 'Sayadzada', 'BCS');
INSERT INTO STUDENTS VALUES(4, 'Aytan', 'Salmanli', 'BBA');
INSERT INTO STUDENTS VALUES(5, 'Ulkar', 'Alaskarova','BBA');
INSERT INTO STUDENTS VALUES(6, 'Emil', 'Suleymanli', 'BBA');
INSERT INTO STUDENTS VALUES(7, 'Abduljalil', 'Kazimov', 'BCE');
INSERT INTO STUDENTS VALUES(8, 'Mahammad', 'Aliyev', 'BCE');


INSERT INTO COURSES VALUES(1101, 'Principles of Microeconomics');
INSERT INTO COURSES VALUES(1102, 'Web & Mobile 2');
INSERT INTO COURSES VALUES(1103, 'Probability & Statistics');
INSERT INTO COURSES VALUES(1104, 'Principles of Marketing');
INSERT INTO COURSES VALUES(1105, 'System Analysis & Design');

INSERT INTO ENROLLMENTS VALUES(1,1101);
INSERT INTO ENROLLMENTS VALUES(1,1102);
INSERT INTO ENROLLMENTS VALUES(1,1103);
INSERT INTO ENROLLMENTS VALUES(1,1104);
INSERT INTO ENROLLMENTS VALUES(1,1105);

INSERT INTO ENROLLMENTS VALUES(2,1101);
INSERT INTO ENROLLMENTS VALUES(2,1102);
INSERT INTO ENROLLMENTS VALUES(2,1103);

INSERT INTO ENROLLMENTS VALUES(3,1103);
INSERT INTO ENROLLMENTS VALUES(3,1105);

INSERT INTO ENROLLMENTS VALUES(4,1101);
INSERT INTO ENROLLMENTS VALUES(4,1104);

INSERT INTO ENROLLMENTS VALUES(5,1101);
INSERT INTO ENROLLMENTS VALUES(5,1104);

INSERT INTO ENROLLMENTS VALUES(6,1101);
INSERT INTO ENROLLMENTS VALUES(6,1104);

INSERT INTO ENROLLMENTS VALUES(7,1101);
INSERT INTO ENROLLMENTS VALUES(7,1103);

INSERT INTO ENROLLMENTS VALUES(8,1101);
INSERT INTO ENROLLMENTS VALUES(8,1103);

